# Generated by Django 3.2.7 on 2021-10-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_post',
            name='count_rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review_post',
            name='rate',
            field=models.IntegerField(null=True),
        ),
    ]
