# Generated by Django 3.2.7 on 2021-10-08 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20211007_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment_post',
            name='company_name',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='recruitment_post',
            name='locations',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
