# Generated by Django 3.2.7 on 2021-10-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20211009_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_post',
            name='count_rate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review_post',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
