# Generated by Django 3.2.7 on 2021-10-13 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20211012_0150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_comments',
            name='rate',
            field=models.FloatField(),
        ),
    ]
