# Generated by Django 3.2.7 on 2021-10-13 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_review_comments_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_comments',
            name='rate',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
