# Generated by Django 3.2.7 on 2021-10-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_review_comments_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review_comments',
            name='rate',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review_post',
            name='count_rate',
            field=models.FloatField(default=0),
        ),
    ]
